classes: {
  cardinality_01_01: {
    source-arrowhead.label: 0..1
    target-arrowhead.label: 0..1
  }

  cardinality_01_1: {
    source-arrowhead.label: 0..1
    target-arrowhead.label: 1
  }

  cardinality_01_0many: {
    source-arrowhead.label: 0..1
    target-arrowhead.label: 0..*
  }

  cardinality_01_1many: {
    source-arrowhead.label: 0..1
    target-arrowhead.label: 1..*
  }

  cardinality_01_many: {
    source-arrowhead.label: 0..1
    target-arrowhead.label: *
  }

  cardinality_1_01: {
    source-arrowhead.label: 1
    target-arrowhead.label: 0..1
  }

  cardinality_1_1: {
    source-arrowhead.label: 1
    target-arrowhead.label: 1
  }

  cardinality_1_0many: {
    source-arrowhead.label: 1
    target-arrowhead.label: 0..*
  }

  cardinality_1_1many: {
    source-arrowhead.label: 1
    target-arrowhead.label: 1..*
  }

  cardinality_1_many: {
    source-arrowhead.label: 1
    target-arrowhead.label: *
  }

  cardinality_0many_01: {
    source-arrowhead.label: 0..*
    target-arrowhead.label: 0..1
  }

  cardinality_0many_1: {
    source-arrowhead.label: 0..*
    target-arrowhead.label: 1
  }

  cardinality_0many_0many: {
    source-arrowhead.label: 0..*
    target-arrowhead.label: 0..*
  }

  cardinality_0many_1many: {
    source-arrowhead.label: 0..*
    target-arrowhead.label: 1..*
  }

  cardinality_0many_many: {
    source-arrowhead.label: 0..*
    target-arrowhead.label: *
  }

  cardinality_1many_01: {
    source-arrowhead.label: 1..*
    target-arrowhead.label: 0..1
  }

  cardinality_1many_1: {
    source-arrowhead.label: 1..*
    target-arrowhead.label: 1
  }

  cardinality_1many_0many: {
    source-arrowhead.label: 1..*
    target-arrowhead.label: 0..*
  }

  cardinality_1many_1many: {
    source-arrowhead.label: 1..*
    target-arrowhead.label: 1..*
  }

  cardinality_1many_many: {
    source-arrowhead.label: 1..*
    target-arrowhead.label: *
  }

  cardinality_many_01: {
    source-arrowhead.label: *
    target-arrowhead.label: 0..1
  }

  cardinality_many_1: {
    source-arrowhead.label: *
    target-arrowhead.label: 1
  }

  cardinality_many_0many: {
    source-arrowhead.label: *
    target-arrowhead.label: 0..*
  }

  cardinality_many_1many: {
    source-arrowhead.label: *
    target-arrowhead.label: 1..*
  }

  cardinality_many_many: {
    source-arrowhead.label: *
    target-arrowhead.label: *
  }
}
