classes: {
  edge_2: {
    style: {
      stroke-dash: 3
      opacity: 0.5
    }
  }

  edge_3: {
    style: {
      opacity: 0.1
    }
  }

  edge_logical: {
    style: {
      stroke-dash: 3
    }
  }

  # Represents all nodes in the graph, 
  # helps to keep the number of edges low
  all_nodes: {
    style: {
      stroke: transparent
      border-radius: 100
    }
    width: 50
    height: 50
  }

  person: {
    width: 65
    height: 70
    style: {
      stroke: transparent
    }
  }
}
